server.port=${SERVER_PORT:9092}
spring.application.name=diabetesassessment
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/medilabo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/medilabo}
jwt.secret=${JWT_SECRET:MediLaboSuperSecretKeyForJwtTokenSigning2026!MustBeAtLeast256Bits}